apiVersion: v1
kind: Service
metadata:
  name: {{ required "Release name must be set" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: 20000
      targetPort: 20000
