apiVersion: v1
kind: Service
metadata:
  name: {{ required "Release name must be set" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 20000
    {{- if .Values.metrics.port }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
    {{- end }}
