name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@00b4f32d76cd9135ec99a441008eab8869e6df13

  publish-chart:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@f02620f44558ae015a17e217a2064d61dda1185d
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: chart
      helm_registry_repository: project-origin/helm-registry
      prerelease: ${{ github.event.release.prerelease }}
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
