name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@00b4f32d76cd9135ec99a441008eab8869e6df13

  publish-chart:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@00b4f32d76cd9135ec99a441008eab8869e6df13
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: chart
      helm_registry_repository: project-origin/helm-registry
      prerelease: ${{ needs.define-version.outputs.prerelease }}
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
