name: Build release artifacts

on:
  release:
    types: [published]

jobs:
  define-version:
    uses: project-origin/.github/.github/workflows/reusable-tag-version.yaml@b1a1034591b6f491085a0d9d259ae3b486487701

  publish-chart:
    needs:
      - define-version
    uses: project-origin/.github/.github/workflows/reusable-publish-chart.yaml@b1a1034591b6f491085a0d9d259ae3b486487701
    with:
      version: ${{ needs.define-version.outputs.version }}
      chart_folder: chart
      helm_registry_repository: project-origin/helm-registry
    secrets:
      helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
